# Generated by Django 4.2.2 on 2023-07-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_mainsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainsettings',
            old_name='ad_1',
            new_name='ad1',
        ),
        migrations.RenameField(
            model_name='mainsettings',
            old_name='ad_2',
            new_name='ad2',
        ),
        migrations.RenameField(
            model_name='mainsettings',
            old_name='ad_3',
            new_name='ad3',
        ),
    ]
