# Generated by Django 4.2.2 on 2023-07-13 09:26

import django.core.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_socialmedia_icon_alter_socialmedia_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='social_media/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
