# Generated by Django 4.2.2 on 2023-07-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_socialmedia_icon'),
        ('common', '0004_rename_ad_1_mainsettings_ad1_and_more'),
    ]

    operations = [
    ]
