# Generated by Django 4.2.2 on 2023-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_merge_20230713_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='ad1',
            field=models.BooleanField(default=True, verbose_name='ad1'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='ad2',
            field=models.BooleanField(default=True, verbose_name='ad2'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='ad3',
            field=models.BooleanField(default=True, verbose_name='ad3'),
        ),
    ]
