# Generated by Django 4.2.2 on 2023-07-14 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(null=True, upload_to='social_media/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
