# Generated by Django 4.2.2 on 2023-07-14 13:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='announcement/%Y/%m/%d', verbose_name='image'),
        ),
    ]
