# Generated by Django 4.2.2 on 2023-07-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOfAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Price of Ad',
                'verbose_name_plural': 'Price of Ads',
            },
        ),
    ]
