# Generated by Django 4.2.2 on 2023-07-28 10:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_priceofad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug_from_lang',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en-us', 'English')], max_length=64, null=True, verbose_name='select the language of the slug'),
        ),
    ]
