# Generated by Django 4.2.2 on 2023-09-06 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_rename_title_en_us_ad_title_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staticpage",
            name="slug_from_lang",
        ),
    ]
