# Generated by Django 4.2.2 on 2023-09-14 13:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_remove_staticpage_slug_from_lang"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated date"),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="media/%Y/%m/%d",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Image",
                "verbose_name_plural": "Media Images",
            },
        ),
    ]
