# Generated by Django 4.2.2 on 2023-09-14 13:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_mediaimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="image/%Y/%m/%d",
                verbose_name="image",
            ),
        ),
    ]
