# Generated by Django 4.2.2 on 2024-02-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_mediaimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_ads', to='common.ad', verbose_name='ad')),
            ],
            options={
                'verbose_name': 'Header ad',
                'verbose_name_plural': 'Header ads',
            },
        ),
    ]
