# Generated by Django 4.2.2 on 2023-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uznewsuz_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='UzNewsUz ID'),
        ),
    ]
