# Generated by Django 4.2.2 on 2023-09-06 13:42

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="author/background_image/",
                verbose_name="Background image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Facebook"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=255, null=True, verbose_name="Position"),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Telegram"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Twitter"
            ),
        ),
    ]
