# Generated by Django 4.2.2 on 2023-09-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_background_image_user_facebook_user_instagram_and_more'),
        ('users', '0004_user_uznewsuz_id'),
    ]

    operations = [
    ]
